### PR TITLE
Add sqflint check to integration

### PR DESCRIPTION
**Pull request by ArwynFr**

### CODE REVIEW

**Comment by ArwynFr** [comment]
@ImplicitDeny can you check the integration outcome ?
SQFlint returns a lot of errors, are they legitimate in your opinion ?

**Comment by ImplicitDeny** [comment]
As I already told you, linting in SQF in not very reliable. Any variable declared in other ways than with direct assignation or `private` command is reported as global (which is indeed a bad practice) or undeclared (which is an error). The current linter I experienced with has this issue of misreporting all parameter-passed variables, and all SQF "magic variable" such as `_x` or `_this`.

From what I can see at first glance, all reported errors are due to parameters and magic variables. Soooo... linter's fault I guess ? Cannot fix all that, as these variables are correctly used in my code.

**Comment by ImplicitDeny** [comment]
However there is some "unused variables" that I can get rid of. But it is less that 5% of reported errors.

**Comment by ImplicitDeny** [comment]
@ArwynFr what do you want to do with that ?

**Comment by ArwynFr** [comment]
Les histoire de variables sont reloues mais ce ne sont que de warning.

Par contre, est-ce que ceci est légitime ?

```
gsri_opex/functions/fremm/fn_initFremm.sqf
	[7,53]:error:Binary operator "forEach" arguments must be [(Code,Array)] (lhs is Code, rhs is Nothing)
```

**Comment by ImplicitDeny** [comment]
Sorry, I only speak english on Github 😛 
It's a bit strange, but there is a small copy-paste error that I can fix, maybe this error will disappear

**Pull request merged**
